# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8d3f875434c7699825ada947d6ab9b626752e83219d84ad1ad05fe4ae8087a33cdfd08c875235f92e289baeaf18d057734740e277bf9d8dfbc7a353383a5b4f

test:
  secret_key_base: 5ec32511679716648ed4d04c5f602ab42686c897763485b8a0bd62be3b7a9723dc4d2571d69377929127ee99b5806eafb8b0e10e31783fc4079ff270d6d12ade

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
